-- Project Management API schema for Supabase PostgreSQL.
-- Run this file once in Supabase Dashboard > SQL Editor.

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null unique,
    email_verified_at timestamptz null,
    password varchar(255) not null,
    remember_token varchar(100) null,
    role varchar(32) not null default 'TEAM_MEMBER',
    created_at timestamptz null,
    updated_at timestamptz null,
    constraint users_role_check check (role in ('ADMIN', 'PROJECT_MANAGER', 'TEAM_MEMBER', 'CLIENT'))
);

create table if not exists public.password_reset_tokens (
    email varchar(255) primary key,
    token varchar(255) not null,
    created_at timestamptz null
);

create table if not exists public.sessions (
    id varchar(255) primary key,
    user_id bigint null,
    ip_address varchar(45) null,
    user_agent text null,
    payload text not null,
    last_activity integer not null
);

create index if not exists sessions_user_id_index on public.sessions (user_id);
create index if not exists sessions_last_activity_index on public.sessions (last_activity);

create table if not exists public.projects (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    description text not null,
    status varchar(16) not null default 'AKTIF',
    start_date date not null,
    end_date date not null,
    progress smallint not null default 0,
    owner_id bigint not null,
    created_at timestamptz null,
    updated_at timestamptz null,
    constraint projects_status_check check (status in ('AKTIF', 'DITUNDA', 'SELESAI')),
    constraint projects_progress_check check (progress between 0 and 100),
    constraint projects_owner_id_foreign foreign key (owner_id) references public.users (id) on delete cascade
);

create index if not exists projects_owner_id_index on public.projects (owner_id);

create table if not exists public.tasks (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    title varchar(255) not null,
    description text not null,
    status varchar(16) not null default 'TODO',
    priority varchar(16) not null default 'MEDIUM',
    progress smallint null default 0,
    deadline date null,
    assignee_id bigint null,
    story_points integer not null default 0,
    created_at timestamptz null,
    updated_at timestamptz null,
    constraint tasks_status_check check (status in ('TODO', 'IN_PROGRESS', 'REVIEW', 'DONE')),
    constraint tasks_priority_check check (priority in ('LOW', 'MEDIUM', 'HIGH')),
    constraint tasks_progress_check check (progress is null or progress between 0 and 100),
    constraint tasks_story_points_check check (story_points >= 0),
    constraint tasks_project_id_foreign foreign key (project_id) references public.projects (id) on delete cascade,
    constraint tasks_assignee_id_foreign foreign key (assignee_id) references public.users (id) on delete set null
);

create index if not exists tasks_project_id_index on public.tasks (project_id);
create index if not exists tasks_assignee_id_index on public.tasks (assignee_id);

create table if not exists public.comments (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    task_id bigint null,
    author_id bigint not null,
    content text not null,
    created_at timestamptz null,
    updated_at timestamptz null,
    constraint comments_project_id_foreign foreign key (project_id) references public.projects (id) on delete cascade,
    constraint comments_task_id_foreign foreign key (task_id) references public.tasks (id) on delete cascade,
    constraint comments_author_id_foreign foreign key (author_id) references public.users (id) on delete cascade
);

create index if not exists comments_project_id_index on public.comments (project_id);
create index if not exists comments_task_id_index on public.comments (task_id);
create index if not exists comments_author_id_index on public.comments (author_id);

create table if not exists public.attachments (
    id bigint generated by default as identity primary key,
    comment_id bigint not null,
    name varchar(255) not null,
    size bigint not null,
    path varchar(255) not null,
    created_at timestamptz null,
    updated_at timestamptz null,
    constraint attachments_comment_id_foreign foreign key (comment_id) references public.comments (id) on delete cascade
);

create index if not exists attachments_comment_id_index on public.attachments (comment_id);

create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    title varchar(255) not null,
    message text not null,
    kind varchar(16) not null default 'INFO',
    read boolean not null default false,
    created_at timestamptz null,
    updated_at timestamptz null,
    constraint notifications_kind_check check (kind in ('INFO', 'PROJECT', 'TASK', 'COMMENT')),
    constraint notifications_user_id_foreign foreign key (user_id) references public.users (id) on delete cascade
);

create index if not exists notifications_user_id_index on public.notifications (user_id);

create table if not exists public.activities (
    id bigint generated by default as identity primary key,
    actor_id bigint not null,
    message text not null,
    created_at timestamptz null,
    updated_at timestamptz null,
    constraint activities_actor_id_foreign foreign key (actor_id) references public.users (id) on delete cascade
);

create index if not exists activities_actor_id_index on public.activities (actor_id);

create table if not exists public.personal_access_tokens (
    id bigint generated by default as identity primary key,
    tokenable_type varchar(255) not null,
    tokenable_id bigint not null,
    name text not null,
    token varchar(64) not null unique,
    abilities text null,
    last_used_at timestamptz null,
    expires_at timestamptz null,
    created_at timestamptz null,
    updated_at timestamptz null
);

create index if not exists personal_access_tokens_tokenable_index
    on public.personal_access_tokens (tokenable_type, tokenable_id);
create index if not exists personal_access_tokens_expires_at_index
    on public.personal_access_tokens (expires_at);

create table if not exists public.cache (
    key varchar(255) primary key,
    value text not null,
    expiration bigint not null
);

create table if not exists public.cache_locks (
    key varchar(255) primary key,
    owner varchar(255) not null,
    expiration bigint not null
);

create index if not exists cache_expiration_index on public.cache (expiration);
create index if not exists cache_locks_expiration_index on public.cache_locks (expiration);

create table if not exists public.jobs (
    id bigint generated by default as identity primary key,
    queue varchar(255) not null,
    payload text not null,
    attempts smallint not null,
    reserved_at integer null,
    available_at integer not null,
    created_at integer not null
);

create index if not exists jobs_queue_index on public.jobs (queue);

create table if not exists public.job_batches (
    id varchar(255) primary key,
    name varchar(255) not null,
    total_jobs integer not null,
    pending_jobs integer not null,
    failed_jobs integer not null,
    failed_job_ids text not null,
    options text null,
    cancelled_at integer null,
    created_at integer not null,
    finished_at integer null
);

create table if not exists public.failed_jobs (
    id bigint generated by default as identity primary key,
    uuid varchar(255) not null unique,
    connection text not null,
    queue text not null,
    payload text not null,
    exception text not null,
    failed_at timestamptz not null default now()
);

create index if not exists failed_jobs_connection_queue_failed_at_index
    on public.failed_jobs (connection, queue, failed_at);
